Updated comments

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,11 +18,9 @@ aliases:
 
   - &spec_test |
       go test -v -race ./spec
-      set +e
-      # If we don't have any tags we will get exit code 128.
-      # Ignore it, the last diff is what's important here.
+      set +e # If we don't have any tags we will get exit code 128.
       TAG=$(git describe --tags --abbrev=0 2> /dev/null)
-      set -e
+      set -e # Reset -e just in case
       if [[ ! -z $TAG && ($(git rev-list -n 1 $TAG) == $(git rev-parse HEAD)) ]]; then
         go run ./spec/generate.go -version $TAG
       else
